package DCRS_1Corba;


/**
* DCRS_1Corba/InterfaceCorbaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/iknoor/eclipse-workspace2018/DCRS_1/bin/InterfaceCorba.idl
* Sunday, November 4, 2018 4:05:19 PM EST
*/

public abstract class InterfaceCorbaPOA extends org.omg.PortableServer.Servant
 implements DCRS_1Corba.InterfaceCorbaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addCourse", new java.lang.Integer (0));
    _methods.put ("removeCourse", new java.lang.Integer (1));
    _methods.put ("listCourseAvailability", new java.lang.Integer (2));
    _methods.put ("enrolCourse", new java.lang.Integer (3));
    _methods.put ("getClassSchedule", new java.lang.Integer (4));
    _methods.put ("dropCourse", new java.lang.Integer (5));
    _methods.put ("swapCourse", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DCRS_1Corba/InterfaceCorba/addCourse
       {
         String courseID = in.read_string ();
         String semester = in.read_string ();
         String capacity = in.read_string ();
         boolean $result = false;
         $result = this.addCourse (courseID, semester, capacity);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // DCRS_1Corba/InterfaceCorba/removeCourse
       {
         String courseID = in.read_string ();
         String semester = in.read_string ();
         boolean $result = false;
         $result = this.removeCourse (courseID, semester);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // DCRS_1Corba/InterfaceCorba/listCourseAvailability
       {
         String semester = in.read_string ();
         String $result = null;
         $result = this.listCourseAvailability (semester);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // DCRS_1Corba/InterfaceCorba/enrolCourse
       {
         String studentID = in.read_string ();
         String courseID = in.read_string ();
         String semester = in.read_string ();
         String $result = null;
         $result = this.enrolCourse (studentID, courseID, semester);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // DCRS_1Corba/InterfaceCorba/getClassSchedule
       {
         String studentID = in.read_string ();
         String $result = null;
         $result = this.getClassSchedule (studentID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // DCRS_1Corba/InterfaceCorba/dropCourse
       {
         String studentID = in.read_string ();
         String courseID = in.read_string ();
         boolean $result = false;
         $result = this.dropCourse (studentID, courseID);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // DCRS_1Corba/InterfaceCorba/swapCourse
       {
         String studentID = in.read_string ();
         String oldcourseID = in.read_string ();
         String newcourseID = in.read_string ();
         String $result = null;
         $result = this.swapCourse (studentID, oldcourseID, newcourseID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DCRS_1Corba/InterfaceCorba:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public InterfaceCorba _this() 
  {
    return InterfaceCorbaHelper.narrow(
    super._this_object());
  }

  public InterfaceCorba _this(org.omg.CORBA.ORB orb) 
  {
    return InterfaceCorbaHelper.narrow(
    super._this_object(orb));
  }


} // class InterfaceCorbaPOA
