package DCRS_1Corba;


/**
* DCRS_1Corba/InterfaceCorbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/iknoor/eclipse-workspace2018/DCRS_1/bin/InterfaceCorba.idl
* Sunday, November 4, 2018 4:05:19 PM EST
*/

public interface InterfaceCorbaOperations 
{
  boolean addCourse (String courseID, String semester, String capacity);
  boolean removeCourse (String courseID, String semester);
  String listCourseAvailability (String semester);
  String enrolCourse (String studentID, String courseID, String semester);
  String getClassSchedule (String studentID);
  boolean dropCourse (String studentID, String courseID);
  String swapCourse (String studentID, String oldcourseID, String newcourseID);
} // interface InterfaceCorbaOperations
