package DCRS_1Corba;


/**
* DCRS_1Corba/InterfaceCorba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/iknoor/eclipse-workspace2018/DCRS_1/bin/InterfaceCorba.idl
* Sunday, November 4, 2018 4:05:19 PM EST
*/

public interface InterfaceCorba extends InterfaceCorbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InterfaceCorba
